const state=loadState();const els=Object.fromEntries([...document.querySelectorAll('[id]')].map(el=>[el.id,el]));let dragging=null;
const fill=(el,items,val)=>el.innerHTML=items.map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('');
function init(){fill(els.plannerJob,Object.keys(state.jobs),state.selection.job);fill(els.plannerEncounter,Object.keys(state.encounters),state.selection.encounter);els.plannerJob.onchange=()=>{state.selection.job=els.plannerJob.value;saveState(state);render();};els.plannerEncounter.onchange=()=>{state.selection.encounter=els.plannerEncounter.value;saveState(state);render();};render();}
function render(){const job=state.jobs[state.selection.job],enc=state.encounters[state.selection.encounter];renderPalette(els.gcdPalette,job.skills.filter(s=>s.type==='gcd'));renderPalette(els.ogcdPalette,job.skills.filter(s=>s.type==='ogcd'));els.timeline.innerHTML='';const bar=document.createElement('div');bar.className='timeline-bar';[...enc.events].sort((a,b)=>a.time-b.time).forEach(e=>{const c=document.createElement('div');c.className='time-col';c.style.left=`${e.time*8}px`;c.innerHTML=`<div class='time-label'>${fmt(e.time)}<br>${e.name}</div>`;c.append(lane(e.time,'gcd'),lane(e.time,'ogcd'));bar.appendChild(c);});bar.style.width=`${Math.max(900,((enc.events.at(-1)?.time||120)*8+240))}px`;els.timeline.appendChild(bar);paint();}
function lane(time,type){const el=document.createElement('div');el.className=`lane ${type}`;el.dataset.time=time;el.dataset.lane=type;el.ondragover=e=>{e.preventDefault();el.classList.add('active')};el.ondragleave=()=>el.classList.remove('active');el.ondrop=e=>{e.preventDefault();el.classList.remove('active');if(!dragging)return;const skill=findSkill(dragging);if(!skill||skill.type!==type)return;const r=canPlace({time,lane:type,skillId:skill.id});if(!r.ok)return status(r.reason,'warn');state.actions.push({id:crypto.randomUUID(),time,lane:type,skillId:skill.id});saveState(state);render();};return el;}
function canPlace(a){const t=state.actions.filter(x=>x.time===a.time),g=t.filter(x=>x.lane==='gcd'),o=t.filter(x=>x.lane==='ogcd');const s=findSkill(a.skillId);if(a.lane==='gcd'&&g.length>=1)return{ok:false,reason:'同点最多1个GCD'};if(a.lane==='ogcd'){if(g.length<1)return{ok:false,reason:'先放GCD'};if(o.length>=2)return{ok:false,reason:'同点最多2个能力技'};if(s.cast>0&&o.length>=1)return{ok:false,reason:'有咏唱能力技同点仅1个'};}return{ok:true};}
function renderPalette(ct,skills){ct.innerHTML='';skills.forEach(s=>{const n=document.getElementById('skill-template').content.firstElementChild.cloneNode(true);n.querySelector('img').src=s.icon||DEFAULT_ICON;n.querySelector('.label').textContent=s.name;n.ondragstart=()=>dragging=s.id;ct.appendChild(n);});}
function paint(){document.querySelectorAll('.lane').forEach(l=>{const t=Number(l.dataset.time),k=l.dataset.lane;state.actions.filter(a=>a.time===t&&a.lane===k).forEach(a=>{const s=findSkill(a.skillId);if(!s)return;const n=document.getElementById('skill-template').content.firstElementChild.cloneNode(true);n.querySelector('img').src=s.icon||DEFAULT_ICON;n.querySelector('.label').textContent=s.name;const b=document.createElement('button');b.textContent='×';b.className='danger';b.onclick=()=>{state.actions=state.actions.filter(x=>x.id!==a.id);saveState(state);render();};n.appendChild(b);l.appendChild(n);});});}
const findSkill=id=>Object.values(state.jobs).flatMap(j=>j.skills).find(s=>s.id===id);const fmt=x=>`${Math.floor(x/60)}:${String(Math.floor(x%60)).padStart(2,'0')}`;const status=(m,l)=>{els.status.textContent=m;els.status.className=`status ${l}`};init();
